package org.mposolda.drools.uripolicytest;

import org.drools.WorkingMemory;
import org.mposolda.drools.uripolicytest.Result;
import org.mposolda.drools.uripolicytest.Decision;
import org.mposolda.drools.uripolicytest.UriPolicyInput;
import org.mposolda.drools.uripolicytest.Token;
import org.mposolda.drools.uripolicytest.MatcherInfo;
import java.util.List;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

dialect "mvel"

function boolean matches(String regex, String textToMatch, MatcherInfo mi) {
  if (mi.isProcessed()) {
    System.out.println("regex: " + regex + ", textToMatch: " + textToMatch + " already processed with result: " + mi);
    return mi.isMatched();
  }

  System.out.println("regex: " + regex + ", textToMatch: " + textToMatch + " - start processing");
  Pattern p = Pattern.compile(regex);
  Matcher m = p.matcher(textToMatch);

  if (m.find()) {
    mi.setMatched(true);

    for (int i=0 ; i<=m.groupCount() ; i++) {
      mi.addGroup(m.group(i));
    }
  } else {
    mi.setMatched(false);
  }

  mi.setProcessed(true);
  System.out.println("Going to return mi: " + mi);
  return mi.isMatched();
}


function String any(List items) {
  String result = "";
  for (int i=0 ; i<items.size() ; i++) {
    String item = (String)items.get(i);
    if (i > 0) {
        result = result + "|";
    }
    result = result + item;
  }
  return result;
}